server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  security:
    user:
      name: test
      password: 1q2w3e4r!

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://shc-db.cgogdkhaohzu.ap-northeast-2.rds.amazonaws.com:3306/goodneighbors-1114
    username: admin
    password: 1q2w3e4r1

mybatis:
  mapper-locations:
    - /mappers/*.xml